/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import MenuFormatter.IMenuFormatter;
import RestaurantMenuCreatorFactory.MenuCreatorAbstractFactory;
import RestaurantMenuCreatorFactory.MenuCreatorAbstractFactoryClient;

/**
 *
 * @author charles
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    private  MainPageSingleton menuCombination= MainPageSingleton.getInstance();
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        GBRationBtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        USRationBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        DinerRationBtn = new javax.swing.JRadioButton();
        EveningRationBtn = new javax.swing.JRadioButton();
        AllDayRationBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        TXTRationBtn = new javax.swing.JRadioButton();
        HTMLRationBtn = new javax.swing.JRadioButton();
        XMLRationBtn = new javax.swing.JRadioButton();
        GenerateBtn = new javax.swing.JButton();
        PathText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Restaurants Menu Creator");

        GBRationBtn.setText("Great Brtain");
        GBRationBtn.setActionCommand("Great Britain");
        GBRationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBRationBtnActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Country:");

        USRationBtn.setText("United States");
        USRationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USRationBtnActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Restaurant Type:");

        DinerRationBtn.setText("Diner");
        DinerRationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DinerRationBtnActionPerformed(evt);
            }
        });

        EveningRationBtn.setText("Evening");
        EveningRationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EveningRationBtnActionPerformed(evt);
            }
        });

        AllDayRationBtn.setText("All Day");
        AllDayRationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllDayRationBtnActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Menu Format:");

        TXTRationBtn.setText("Plain Text");
        TXTRationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRationBtnActionPerformed(evt);
            }
        });

        HTMLRationBtn.setText("HTML");
        HTMLRationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HTMLRationBtnActionPerformed(evt);
            }
        });

        XMLRationBtn.setText("XML");
        XMLRationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XMLRationBtnActionPerformed(evt);
            }
        });

        GenerateBtn.setText("Generate Menu");
        GenerateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBtnActionPerformed(evt);
            }
        });

        PathText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathTextActionPerformed(evt);
            }
        });

        jLabel6.setText("File Path:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(96, 96, 96)
                                .add(jLabel1))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                            .add(69, 69, 69)
                                            .add(jLabel2))
                                        .add(layout.createSequentialGroup()
                                            .add(24, 24, 24)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(jLabel6)
                                                .add(jLabel3))))
                                    .add(jLabel4))
                                .add(58, 58, 58)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(DinerRationBtn)
                                            .add(TXTRationBtn)
                                            .add(GBRationBtn))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(HTMLRationBtn)
                                                    .add(EveningRationBtn))
                                                .add(18, 18, 18)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(AllDayRationBtn)
                                                    .add(XMLRationBtn)))
                                            .add(USRationBtn)))
                                    .add(GenerateBtn))))
                        .add(0, 58, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PathText))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(Message, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 401, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(GBRationBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(USRationBtn))
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(DinerRationBtn)
                    .add(EveningRationBtn)
                    .add(AllDayRationBtn))
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(TXTRationBtn)
                    .add(HTMLRationBtn)
                    .add(XMLRationBtn))
                .add(18, 18, 18)
                .add(GenerateBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel6)
                .add(1, 1, 1)
                .add(PathText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(Message)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GBRationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBRationBtnActionPerformed
        // TODO add your handling code here:
        buttonGroup1.add(GBRationBtn);
        buttonGroup1.add(USRationBtn);
        menuCombination.setCountry("GB");
        
    }//GEN-LAST:event_GBRationBtnActionPerformed

    private void AllDayRationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllDayRationBtnActionPerformed
        // TODO add your handling code here:
        buttonGroup2.add(DinerRationBtn);
        buttonGroup2.add(EveningRationBtn);
        buttonGroup2.add(AllDayRationBtn);
        menuCombination.setMenuCategory("AllDay");
    }//GEN-LAST:event_AllDayRationBtnActionPerformed

    private void DinerRationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DinerRationBtnActionPerformed
        // TODO add your handling code here:
        buttonGroup2.add(DinerRationBtn);
        buttonGroup2.add(EveningRationBtn);
        buttonGroup2.add(AllDayRationBtn);
        menuCombination.setMenuCategory("Diner");
        
    }//GEN-LAST:event_DinerRationBtnActionPerformed

    private void USRationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USRationBtnActionPerformed
        // TODO add your handling code here:
         buttonGroup1.add(GBRationBtn);
         buttonGroup1.add(USRationBtn);
         menuCombination.setCountry("US");
    }//GEN-LAST:event_USRationBtnActionPerformed

    private void EveningRationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EveningRationBtnActionPerformed
        // TODO add your handling code here:
        buttonGroup2.add(DinerRationBtn);
        buttonGroup2.add(EveningRationBtn);
        buttonGroup2.add(AllDayRationBtn);
        menuCombination.setMenuCategory("Evening");
    }//GEN-LAST:event_EveningRationBtnActionPerformed

    private void TXTRationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRationBtnActionPerformed
        // TODO add your handling code here:
        buttonGroup3.add(TXTRationBtn);
        buttonGroup3.add(HTMLRationBtn);
        buttonGroup3.add(XMLRationBtn);
        menuCombination.setMenuFormat("TXT");
    }//GEN-LAST:event_TXTRationBtnActionPerformed

    private void HTMLRationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HTMLRationBtnActionPerformed
        // TODO add your handling code here:
        buttonGroup3.add(TXTRationBtn);
        buttonGroup3.add(HTMLRationBtn);
        buttonGroup3.add(XMLRationBtn);
        menuCombination.setMenuFormat("HTML");
    }//GEN-LAST:event_HTMLRationBtnActionPerformed

    private void XMLRationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XMLRationBtnActionPerformed
        // TODO add your handling code here:
        buttonGroup3.add(TXTRationBtn);
        buttonGroup3.add(HTMLRationBtn);
        buttonGroup3.add(XMLRationBtn);
        menuCombination.setMenuFormat("XML");
    }//GEN-LAST:event_XMLRationBtnActionPerformed

    private void GenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBtnActionPerformed
        // TODO add your handling code here:
        MenuCreatorAbstractFactory menuCreatorAbstractFactory=MenuCreatorAbstractFactoryClient.getAbstractFactory
                 (menuCombination.getCountry(), menuCombination.getMenuCategory(), menuCombination.getMenuFormat());
          IMenuFormatter  menuFormatter = menuCreatorAbstractFactory.createMenuFormatter();
          String FileName=menuFormatter.generateMenu(menuCombination.getCountry(),menuCombination.getMenuCategory());
          PathText.setText(System.getProperty("user.dir")+"/"+FileName);
          String message="Generate "+FileName+" Successfully!";
          Message.setText(message);
 
    }//GEN-LAST:event_GenerateBtnActionPerformed

    private void PathTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PathTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AllDayRationBtn;
    private javax.swing.JRadioButton DinerRationBtn;
    private javax.swing.JRadioButton EveningRationBtn;
    private javax.swing.JRadioButton GBRationBtn;
    private javax.swing.JButton GenerateBtn;
    private javax.swing.JRadioButton HTMLRationBtn;
    private javax.swing.JLabel Message;
    private javax.swing.JTextField PathText;
    private javax.swing.JRadioButton TXTRationBtn;
    private javax.swing.JRadioButton USRationBtn;
    private javax.swing.JRadioButton XMLRationBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
